services:
  mongo:
    image: mongo
    container_name: mongo-nest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: freddy
      MONGO_INITDB_ROOT_PASSWORD: freddy123
    volumes:
      - mongo_data:/data/db

  nestjs:
    build: .
    container_name: nest-dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  
volumes:
  mongo_data:
